# -*- coding: utf-8 -*-
"""Arvore-de-decisao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rtFV9krBKw1J75KKHznbH2bUC9MChqZd
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.metrics import accuracy_score

# ---------------------------------------------------------
# 1. CARREGAMENTO E TRATAMENTO DOS DADOS
# ---------------------------------------------------------
url = "https://docs.google.com/spreadsheets/d/1g1aQ61vijh6uHJuc8sijeBEMsoIQ2a5yLwUK04Wptlg/export?format=csv"
df = pd.read_csv(url)

mapping = {
    "Carimbo de data/hora": "timestamp",
    "Você ficou gripado no ano passado ?": "gripe_ano_passado",
    "Você tomou vacina da gripe no ano passado?": "vacina",
    "  Você frequentou no ano passado,  semanalmente ambientes com muitas pessoas? (salas cheias, ônibus, eventos, etc.)  ": "ambientes_cheios",
    "  Você viajou no ano passado mais de 100 km de distância?  ": "viajou",
    "  Você tem alergia nas vias aéreas (rinite, sinusite, etc.)?  ": "alergia",
    "Quantas horas você dormiu em média por noite no ano passado?": "horas_sono",
    "Você praticou atividade física no ano passado?": "exercicio",
    "Você se alimentou de forma balanceada no ano passado?": "alimentacao",
    "Em média, quantas vezes você lavou as mãos por dia no ano passado?": "lavagem_maos",
    "Na sua percepção, o seu nível de estresse no ano passado foi:": "estresse"
}

df_cleaned = df.rename(columns=mapping).dropna()

mappings = {
    'gripe_ano_passado': {'Sim': 1, 'Não': 0},
    'vacina': {'Sim': 1, 'Não': 0},
    'ambientes_cheios': {'Sim': 1, 'Não': 0},
    'exercicio': {'Sim': 1, 'Não': 0},
    'viajou': {'Nuca': 0, 'Poucas vezes por ano': 0.5, 'Pelo menos uma vez por mês': 1},
    'alergia': {'Não': 0, 'Pouco': 0.3, 'Médio': 0.5, 'Muito': 1},
    'horas_sono': {'4 horas ou menos': 0.2, 'entre 4 e 6 horas': 0.5, 'mais de 6 horas': 0.9},
    'alimentacao': {'Não, raramente': 0, 'Às vezes': 0.5, 'Sim, a maior parte do tempo': 1},
    'lavagem_maos': {'2 vezes ou menos': 0.2, '3 a 5 vezes': 0.5, '6 a 10 vezes': 0.8, 'Mais de 10 vezes': 1},
    'estresse': {1: 0.2, 2: 0.4, 3: 0.6, 4: 0.8, 5: 1}
}

df_encoded = df_cleaned.copy()
for col, map_dict in mappings.items():
    if col in df_encoded.columns:
        df_encoded[col] = df_encoded[col].map(map_dict)

df_encoded = df_encoded.dropna()

X = df_encoded.drop(columns=['timestamp', 'gripe_ano_passado'])
y = df_encoded['gripe_ano_passado']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# ---------------------------------------------------------
# 2. TREINAMENTO DA ÁRVORE DE DECISÃO
# ---------------------------------------------------------
# deixei max_depth=3 para a imagem não ficar gigantesca e ilegível
arvore_model = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=42)
arvore_model.fit(X_train, y_train)

# ---------------------------------------------------------
# 3. VISUALIZAÇÃO DA ÁRVORE (A grande diferença!)
# ---------------------------------------------------------
plt.figure(figsize=(20, 10))
plot_tree(arvore_model,
          feature_names=list(X.columns),
          class_names=['Não Gripou', 'Gripou'],
          filled=True,
          rounded=True,
          fontsize=10)

plt.title("Árvore de Decisão - Previsão de Gripe", fontsize=16)
plt.show()

# ---------------------------------------------------------
# 4. AVALIAÇÃO
# ---------------------------------------------------------
y_pred = arvore_model.predict(X_test)
print(f"\nAcurácia da Árvore de Decisão: {accuracy_score(y_test, y_pred) * 100:.2f}%")