# -*- coding: utf-8 -*-
"""KNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13U6mL8QPg62AAhQICjdJulIzBS56vNsJ
"""

import pandas as pd

# URL dos dados
url = "https://docs.google.com/spreadsheets/d/1g1aQ61vijh6uHJuc8sijeBEMsoIQ2a5yLwUK04Wptlg/export?format=csv"

# Carregar dados
df = pd.read_csv(url)

# Mapeamento para nomes simples e sem espaços
mapping = {
    "Carimbo de data/hora": "timestamp",
    "Você ficou gripado no ano passado ?": "gripe_ano_passado",
    "Você tomou vacina da gripe no ano passado?": "vacina",
    "  Você frequentou no ano passado,  semanalmente ambientes com muitas pessoas? (salas cheias, ônibus, eventos, etc.)  ": "ambientes_cheios",
    "  Você viajou no ano passado mais de 100 km de distância?  ": "viajou",
    "  Você tem alergia nas vias aéreas (rinite, sinusite, etc.)?  ": "alergia",
    "Quantas horas você dormiu em média por noite no ano passado?": "horas_sono",
    "Você praticou atividade física no ano passado?": "exercicio",
    "Você se alimentou de forma balanceada no ano passado?": "alimentacao",
    "Em média, quantas vezes você lavou as mãos por dia no ano passado?": "lavagem_maos",
    "Na sua percepção, o seu nível de estresse no ano passado foi:": "estresse"
}

# Renomear e limpar
df_cleaned = df.rename(columns=mapping).dropna()

print("Dados carregados e colunas renomeadas:")
display(df_cleaned.head())

print("Distribuição das classes para 'gripe_ano_passado':")
display(df_cleaned['gripe_ano_passado'].value_counts())

from sklearn.model_selection import train_test_split

# Definindo as variáveis preditoras (X) e a variável alvo (y)
# Removendo a coluna 'timestamp' e o alvo 'gripe_ano_passado'
X = df_cleaned.drop(columns=['timestamp', 'gripe_ano_passado'])
y = df_cleaned['gripe_ano_passado']

# Realizando a divisão: 75% treino e 25% teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

print(f"Tamanho do conjunto de treino: {len(X_train)}")
print(f"Tamanho do conjunto de teste: {len(X_test)}")

# Verificando valores únicos para garantir que o mapeamento funcione
cols_to_check = ['viajou', 'horas_sono', 'lavagem_maos', 'estresse']
print("Valores únicos encontrados nas colunas:")
for col in cols_to_check:
    print(f"{col}: {df_cleaned[col].unique()}")

# Dicionário de mapeamento corrigido (ajustando possíveis variações de texto)
mappings = {
    'gripe_ano_passado': {'Sim': 1, 'Não': 0},
    'vacina': {'Sim': 1, 'Não': 0},
    'ambientes_cheios': {'Sim': 1, 'Não': 0},
    'exercicio': {'Sim': 1, 'Não': 0},
    'viajou': {
        'Nuca': 0,
        'Poucas vezes por ano': 0.5,
        'Pelo menos uma vez por mês': 1
    },
    'alergia': {
        'Não': 0,
        'Pouco': 0.3,
        'Médio': 0.5,
        'Muito': 1
    },
    'horas_sono': {
        '4 horas ou menos': 0.2,
        'entre 4 e 6 horas': 0.5,
        'mais de 6 horas': 0.9
    },
    'alimentacao': {
        'Não, raramente': 0,
        'Às vezes': 0.5,
        'Sim, a maior parte do tempo': 1
    },
    'lavagem_maos': {
        '2 vezes ou menos': 0.2,
        '3 a 5 vezes': 0.5,
        '6 a 10 vezes': 0.8,
        'Mais de 10 vezes': 1
    },
    'estresse': {
        1: 0.2,
        2: 0.4,
        3: 0.6,
        4: 0.8,
        5: 1
    }
}

# Aplicando as transformações e removendo linhas que ainda restarem com NaN se necessário
df_encoded = df_cleaned.copy()
for col, mapping in mappings.items():
    if col in df_encoded.columns:
        df_encoded[col] = df_encoded[col].map(mapping)

print("\nDados transformados em números (após correção):")
display(df_encoded.head(15))

import seaborn as sns
import matplotlib.pyplot as plt

# 1. Resumo estatístico
print("Resumo Estatístico dos Dados:")
display(df_encoded.describe())

# 2. Matriz de correlação
plt.figure(figsize=(12, 8))
correlation_matrix = df_encoded.drop(columns=['timestamp']).corr()

sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f')
plt.title("Matriz de Correlação")
plt.show()

# Mostrar correlação específica com o alvo
print("\nCorrelação das variáveis com 'gripe_ano_passado':")
print(correlation_matrix['gripe_ano_passado'].sort_values(ascending=False))

from sklearn.model_selection import train_test_split

# Separando as variáveis preditoras (X) do alvo (y) usando o dataframe codificado
# Removemos 'timestamp' por ser apenas um identificador
X = df_encoded.drop(columns=['timestamp', 'gripe_ano_passado'])
y = df_encoded['gripe_ano_passado']

# Dividindo em 75% treino e 25% teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

print(f"Conjunto de Treino: {len(X_train)} amostras")
print(f"Conjunto de Teste: {len(X_test)} amostras")

print("\nExemplo das variáveis de treino (X_train):")
display(X_train.head())

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV

# Definindo o modelo base
knn = KNeighborsClassifier()

# Definindo o espaço de busca de hiperparâmetros
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11, 13, 15, 17, 19],
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan', 'minkowski']
}

# Configurando o GridSearchCV com 5-fold cross-validation
grid_search = GridSearchCV(knn, param_grid, cv=5, scoring='accuracy', n_jobs=-1)

# Treinando o grid search
grid_search.fit(X_train, y_train)

# Resultados
print(f"Melhores parâmetros encontrados: {grid_search.best_params_}")
print(f"Melhor acurácia no cross-validation: {grid_search.best_score_:.4f}")

# Avaliando no conjunto de teste
best_model = grid_search.best_estimator_
test_accuracy = best_model.score(X_test, y_test)
print(f"Acurácia final no conjunto de teste: {test_accuracy:.4f}")