# -*- coding: utf-8 -*-
"""Naive-Bayes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCQxBrJ4oomol1DaP-UZI-2yCFsm230g
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# ---------------------------------------------------------
# 1. CARREGAMENTO E TRATAMENTO DOS DADOS
# ---------------------------------------------------------
url = "https://docs.google.com/spreadsheets/d/1g1aQ61vijh6uHJuc8sijeBEMsoIQ2a5yLwUK04Wptlg/export?format=csv"
df = pd.read_csv(url)

mapping = {
    "Carimbo de data/hora": "timestamp",
    "Você ficou gripado no ano passado ?": "gripe_ano_passado",
    "Você tomou vacina da gripe no ano passado?": "vacina",
    "  Você frequentou no ano passado,  semanalmente ambientes com muitas pessoas? (salas cheias, ônibus, eventos, etc.)  ": "ambientes_cheios",
    "  Você viajou no ano passado mais de 100 km de distância?  ": "viajou",
    "  Você tem alergia nas vias aéreas (rinite, sinusite, etc.)?  ": "alergia",
    "Quantas horas você dormiu em média por noite no ano passado?": "horas_sono",
    "Você praticou atividade física no ano passado?": "exercicio",
    "Você se alimentou de forma balanceada no ano passado?": "alimentacao",
    "Em média, quantas vezes você lavou as mãos por dia no ano passado?": "lavagem_maos",
    "Na sua percepção, o seu nível de estresse no ano passado foi:": "estresse"
}

df_cleaned = df.rename(columns=mapping).dropna()

mappings = {
    'gripe_ano_passado': {'Sim': 1, 'Não': 0},
    'vacina': {'Sim': 1, 'Não': 0},
    'ambientes_cheios': {'Sim': 1, 'Não': 0},
    'exercicio': {'Sim': 1, 'Não': 0},
    'viajou': {'Nuca': 0, 'Poucas vezes por ano': 0.5, 'Pelo menos uma vez por mês': 1},
    'alergia': {'Não': 0, 'Pouco': 0.3, 'Médio': 0.5, 'Muito': 1},
    'horas_sono': {'4 horas ou menos': 0.2, 'entre 4 e 6 horas': 0.5, 'mais de 6 horas': 0.9},
    'alimentacao': {'Não, raramente': 0, 'Às vezes': 0.5, 'Sim, a maior parte do tempo': 1},
    'lavagem_maos': {'2 vezes ou menos': 0.2, '3 a 5 vezes': 0.5, '6 a 10 vezes': 0.8, 'Mais de 10 vezes': 1},
    'estresse': {1: 0.2, 2: 0.4, 3: 0.6, 4: 0.8, 5: 1}
}

df_encoded = df_cleaned.copy()
for col, map_dict in mappings.items():
    if col in df_encoded.columns:
        df_encoded[col] = df_encoded[col].map(map_dict)

df_encoded = df_encoded.dropna()

# ---------------------------------------------------------
# 2. SEPARAÇÃO DOS DADOS (Treino e Teste)
# ---------------------------------------------------------
X = df_encoded.drop(columns=['timestamp', 'gripe_ano_passado'])
y = df_encoded['gripe_ano_passado']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# ---------------------------------------------------------
# 3. TREINAMENTO DO MODELO NAIVE BAYES
# ---------------------------------------------------------
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)
y_pred = nb_model.predict(X_test)

# ---------------------------------------------------------
# 4. AVALIAÇÃO DOS RESULTADOS
# ---------------------------------------------------------
print(f"Acurácia Geral do Modelo: {accuracy_score(y_test, y_pred) * 100:.2f}%\n")

print("--- Relatório Detalhado de Classificação ---")
print(classification_report(y_test, y_pred, target_names=['Não Gripou (0)', 'Gripou (1)']))

plt.figure(figsize=(7,5))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, cmap='Blues', fmt='g',
            xticklabels=['Não Gripou', 'Gripou'], yticklabels=['Não Gripou', 'Gripou'])
plt.title('Matriz de Confusão - Naive Bayes Gaussiano')
plt.xlabel('Previsão do Modelo')
plt.ylabel('Realidade (Gabarito)')
plt.show()