# -*- coding: utf-8 -*-
"""Regras-PRISM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dOdWXlpoXYcgS9gQAQheRebbkFnG3HxG
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier, export_text
from sklearn.metrics import accuracy_score

# 1. CARREGAMENTO E TRATAMENTO DOS DADOS (O mesmo de antes)
url = "https://docs.google.com/spreadsheets/d/1g1aQ61vijh6uHJuc8sijeBEMsoIQ2a5yLwUK04Wptlg/export?format=csv"
df = pd.read_csv(url)

mapping = {
    "Carimbo de data/hora": "timestamp",
    "Você ficou gripado no ano passado ?": "gripe_ano_passado",
    "Você tomou vacina da gripe no ano passado?": "vacina",
    "  Você frequentou no ano passado,  semanalmente ambientes com muitas pessoas? (salas cheias, ônibus, eventos, etc.)  ": "ambientes_cheios",
    "  Você viajou no ano passado mais de 100 km de distância?  ": "viajou",
    "  Você tem alergia nas vias aéreas (rinite, sinusite, etc.)?  ": "alergia",
    "Quantas horas você dormiu em média por noite no ano passado?": "horas_sono",
    "Você praticou atividade física no ano passado?": "exercicio",
    "Você se alimentou de forma balanceada no ano passado?": "alimentacao",
    "Em média, quantas vezes você lavou as mãos por dia no ano passado?": "lavagem_maos",
    "Na sua percepção, o seu nível de estresse no ano passado foi:": "estresse"
}

df_cleaned = df.rename(columns=mapping).dropna()

mappings = {
    'gripe_ano_passado': {'Sim': 1, 'Não': 0},
    'vacina': {'Sim': 1, 'Não': 0},
    'ambientes_cheios': {'Sim': 1, 'Não': 0},
    'exercicio': {'Sim': 1, 'Não': 0},
    'viajou': {'Nuca': 0, 'Poucas vezes por ano': 0.5, 'Pelo menos uma vez por mês': 1},
    'alergia': {'Não': 0, 'Pouco': 0.3, 'Médio': 0.5, 'Muito': 1},
    'horas_sono': {'4 horas ou menos': 0.2, 'entre 4 e 6 horas': 0.5, 'mais de 6 horas': 0.9},
    'alimentacao': {'Não, raramente': 0, 'Às vezes': 0.5, 'Sim, a maior parte do tempo': 1},
    'lavagem_maos': {'2 vezes ou menos': 0.2, '3 a 5 vezes': 0.5, '6 a 10 vezes': 0.8, 'Mais de 10 vezes': 1},
    'estresse': {1: 0.2, 2: 0.4, 3: 0.6, 4: 0.8, 5: 1}
}

df_encoded = df_cleaned.copy()
for col, map_dict in mappings.items():
    if col in df_encoded.columns:
        df_encoded[col] = df_encoded[col].map(map_dict)

df_encoded = df_encoded.dropna()

# 2. SEPARAÇÃO DOS DADOS
X = df_encoded.drop(columns=['timestamp', 'gripe_ano_passado'])
y = df_encoded['gripe_ano_passado']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

# 3. TREINAMENTO DO MODELO DE REGRAS (Com Árvore de Decisão)
regras_model = DecisionTreeClassifier(criterion='entropy', max_depth=4, random_state=42)
regras_model.fit(X_train, y_train)

# 4. EXTRAÇÃO E EXIBIÇÃO DAS REGRAS
print("=== REGRAS EXTRAÍDAS DO MODELO ===")
regras_texto = export_text(regras_model, feature_names=list(X.columns))

regras_texto = regras_texto.replace("|---", "SE").replace("|   ", " E ").replace("class: 0.0", "ENTÃO -> Não Gripou").replace("class: 1.0", "ENTÃO -> Gripou")
print(regras_texto)

# Avaliação rápida
y_pred = regras_model.predict(X_test)
print(f"\nAcurácia do Modelo de Regras: {accuracy_score(y_test, y_pred) * 100:.2f}%")